const {onDocumentWritten}=require("firebase-functions/v2/firestore");
const {logger}=require("firebase-functions");
const admin=require("firebase-admin");

admin.initializeApp();
const db=admin.firestore();

function rollString(prefix,start,width,n){
  return String(prefix||"")+String(n).padStart(Math.max(1,Number(width)||6),"0");
}

exports.createAdmitCardDraftOnFinalSubmit=onDocumentWritten("applications/{applicationNumber}",async event=>{
  const after=event.data?.after;
  if(!after?.exists) return null;
  const a=after.data();
  if(a.status!=="Final Submitted") return null;

  const id=event.params.applicationNumber;
  const examId=a.examId||"default";
  const examSnap=await db.doc(`exams/${examId}`).get();
  const exam=examSnap.exists?examSnap.data():{};
  if(exam.autoAdmitDraft===false) return null;
  if(exam.paymentRequired!==false&&a.paymentStatus!=="Successful") return null;

  const ref=db.doc(`admitCards/${id}`);
  const existing=await ref.get();
  const old=existing.exists?existing.data():{};
  if(old.published===true) return null;

  let centre=old.centreCode?{id:old.centreCode,name:old.centreName,address:old.centreAddress,city:old.centreCity,district:old.centreDistrict,state:old.centreState,pin:old.centrePin}:null;
  if(!old.centreCode){
  const centresSnap=await db.collection("centres").where("active","==",true).get();
  const preferred=(centresSnap.docs.map(d=>({id:d.id,...d.data()}))).sort((x,y)=>{
    const city=(a.address?.city||a.address?.district||"").toString().toLowerCase();
    const score=c=>[c.city,c.district,c.state].some(v=>String(v||"").toLowerCase()===city)?0:1;
    return score(x)-score(y);
  });
  if(preferred.length){
    const allocationRef=db.doc(`centreAllocations/${examId}`);
    const selectedId=await db.runTransaction(async tx=>{
      const snap=await tx.get(allocationRef);
      const counts={...(snap.exists?snap.data().counts||{}:{})};
      for(const candidate of preferred){
        const shiftCount=Math.max(1,String(candidate.shifts||"1").split(",").filter(Boolean).length);
        const capacity=Number(candidate.capacity||0);
        const max=capacity>0?capacity*shiftCount:Number.MAX_SAFE_INTEGER;
        const used=Number(counts[candidate.id]||0);
        if(used<max){
          counts[candidate.id]=used+1;
          tx.set(allocationRef,{examId,counts,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});
          return candidate.id;
        }
      }
      return null;
    });
    if(selectedId)centre=preferred.find(x=>x.id===selectedId)||null;
  }
  }

  let rollNumber=old.rollNumber||"";
  if(!rollNumber){
    const counterRef=db.doc(`counters/admit_${examId}`);
    const counter=await db.runTransaction(async tx=>{
      const snap=await tx.get(counterRef);
      const current=Number(snap.exists?snap.data().nextNumber:(
        exam.rollStart??100001
      ));
      if(!Number.isFinite(current)||current<0) throw new Error("Invalid admit roll counter");
      tx.set(counterRef,{
        examId,
        nextNumber:current+1,
        updatedAt:admin.firestore.FieldValue.serverTimestamp()
      },{merge:true});
      return current;
    });
    rollNumber=rollString(exam.rollPrefix,exam.rollStart,exam.rollWidth,counter);
  }

  await ref.set({
    applicationNumber:id,
    authUid:a.authUid,
    candidateName:a.personal?.fullName||"",
    fatherName:a.personal?.fatherName||"",
    examId,
    examName:exam.examName||"",
    examPost:a.personal?.examPost||"",
    examLanguage:a.personal?.examLanguage||exam.language||"",
    examDate:exam.examDate||"",
    requiredId:"Valid Government Photo ID",
    instructions:"Follow all instructions issued by the examination authority.",
    allowedItems:"As per examination instructions.",
    published:false,
    status:old.status||"Draft",
    version:Number(old.version||1),
    rollNumber,
    centreCode:old.centreCode||centre?.id||"",
    centreName:old.centreName||centre?.name||"",
    centreAddress:old.centreAddress||centre?.address||"",
    centreCity:old.centreCity||centre?.city||"",
    centreDistrict:old.centreDistrict||centre?.district||"",
    centreState:old.centreState||centre?.state||"",
    centrePin:old.centrePin||centre?.pin||"",
    centreAssignmentStatus:old.centreCode||centre?"Assigned":"Pending",
    createdAt:old.createdAt||admin.firestore.FieldValue.serverTimestamp(),
    updatedAt:admin.firestore.FieldValue.serverTimestamp(),
    autoGenerated:true
  },{merge:true});

  logger.info("Admit-card draft ensured",{applicationNumber:id,examId,rollNumber});
  return null;
});

exports.initializeOnlineExamAttempt=onDocumentWritten("onlineAttempts/{attemptId}",async event=>{
  const after=event.data?.after;
  if(!after?.exists)return null;
  const a=after.data();
  if(a.status!=="Starting"||a.startedAt||a.expiresAt)return null;
  if(event.params.attemptId!==`${a.examId}_${a.applicationNumber}`)return null;
  const appSnap=await db.doc(`applications/${a.applicationNumber}`).get();
  if(!appSnap.exists)return null;
  const app=appSnap.data();
  if(app.authUid!==a.authUid||!["Final Submitted","Approved"].includes(app.status))return null;
  const examSnap=await db.doc(`exams/${a.examId}`).get();
  if(!examSnap.exists||examSnap.data().onlineExamEnabled!==true||examSnap.data().onlineExamPublished!==true)return null;
  const exam=examSnap.data();
  if(exam.onlineExamRequiresPayment===true&&app.paymentStatus!=="Successful")return null;
  const duration=Math.max(1,Math.min(600,Number(exam.onlineExamDuration||60)));
  const now=admin.firestore.Timestamp.now();
  const expires=admin.firestore.Timestamp.fromMillis(now.toMillis()+duration*60000);
  const qs=await db.collection("onlineQuestions").doc(a.examId).collection("items").where("active","==",true).get();
  let items=qs.docs.map(s=>({id:s.id,...s.data()}));
  if(exam.onlineExamShuffle!==false){
    for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}
  }
  const total=Math.max(1,Math.min(500,Number(exam.onlineExamTotalQuestions||items.length)));
  items=items.slice(0,total);
  const batch=db.batch();
  items.forEach((q,i)=>{
    batch.set(after.ref.collection("questions").doc(q.id),{
      question:q.question,
      options:q.options||[],
      marks:Number(q.marks??exam.onlineExamMarksPerQuestion??1),
      section:q.section||"General",
      order:i+1
    });
  });
  batch.set(after.ref,{
    status:"In Progress",
    startedAt:now,
    expiresAt:expires,
    questionCount:items.length,
    updatedAt:admin.firestore.FieldValue.serverTimestamp()
  },{merge:true});
  await batch.commit();
  return null;
});

exports.gradeOnlineExamAttempt=onDocumentWritten("onlineAttempts/{attemptId}",async event=>{
  const after=event.data?.after;
  if(!after?.exists)return null;
  const a=after.data();
  if(a.status!=="Submitted"||a.graded===true)return null;

  const examSnap=await db.doc(`exams/${a.examId}`).get();
  if(!examSnap.exists)return null;
  const exam=examSnap.data();
  const paperSnap=await after.ref.collection("questions").get();
  const answers=a.answers||{};
  let attempted=0,correct=0,wrong=0,score=0,maxMarks=0;
  const paper=paperSnap.docs.map(s=>({id:s.id,...s.data()}));
  const keySnaps=await Promise.all(paper.map(q=>db.doc(`onlineAnswerKeys/${a.examId}/items/${q.id}`).get()));
  paper.forEach((q,i)=>{
    const keySnap=keySnaps[i];
    if(!keySnap.exists)throw new Error(`Missing answer key for ${q.id}`);
    const k=keySnap.data(), selected=answers[q.id];
    const marks=Math.max(0,Number(k.marks??q.marks??exam.onlineExamMarksPerQuestion??1));
    maxMarks+=marks;
    if(!selected)return;
    attempted++;
    if(String(selected).toUpperCase()===String(k.correct||"").toUpperCase()){
      correct++;
      score+=marks;
    }else{
      wrong++;
      score-=Math.max(0,Number(exam.onlineExamNegativeMark||0));
    }
  });
  score=Math.max(0,Number(score.toFixed(2)));
  const passMarks=Number(exam.onlineExamPassMarks||0);
  const passed=passMarks>0?score>=passMarks:true;
  const appId=a.applicationNumber;
  const appSnap=await db.doc(`applications/${appId}`).get();
  const appData=appSnap.exists?appSnap.data():{};
  const admitSnap=await db.doc(`admitCards/${appId}`).get();
  const admitData=admitSnap.exists?admitSnap.data():{};
  const resultRef=db.doc(`results/${appId}`);
  const resultSnap=await resultRef.get();
  const old=resultSnap.exists?resultSnap.data():{};
  const revision=Number(old.revision||0)+1;
  await db.runTransaction(async tx=>{
    const fresh=await tx.get(after.ref);
    if(!fresh.exists||fresh.data().graded===true)return;
    tx.update(after.ref,{
      graded:true,
      score,
      maximumMarks:maxMarks,
      correct,
      wrong,
      attempted,
      percentage:maxMarks?Number(((score/maxMarks)*100).toFixed(2)):0,
      passed,
      gradedAt:admin.firestore.FieldValue.serverTimestamp(),
      updatedAt:admin.firestore.FieldValue.serverTimestamp()
    });
    tx.set(resultRef,{
      applicationNumber:appId,
      authUid:a.authUid,
      examId:a.examId,
      examName:exam.examName||"",
      rollNumber:admitData.rollNumber||old.rollNumber||"",
      candidateName:appData.personal?.fullName||old.candidateName||"",
      examPost:appData.personal?.examPost||old.examPost||"",
      marksObtained:score,
      finalMarks:score,
      maximumMarks:maxMarks,
      percentage:maxMarks?Number(((score/maxMarks)*100).toFixed(2)):0,
      attempted,
      correct,
      wrong,
      status:passed?"Passed":"Not Passed",
      published:false,
      source:"online-exam",
      onlineAttemptId:event.params.attemptId,
      revision,
      issueDate:new Date().toISOString().slice(0,10),
      updatedAt:admin.firestore.FieldValue.serverTimestamp()
    },{merge:true});
  });
  logger.info("Online exam graded",{attemptId:event.params.attemptId,applicationNumber:appId,score,passed});
  return null;
});


const {onCall,HttpsError,onRequest}=require("firebase-functions/v2/https");
const {defineSecret}=require("firebase-functions/params");
const crypto=require("crypto");

const RAZORPAY_KEY_ID=defineSecret("RAZORPAY_KEY_ID");
const RAZORPAY_KEY_SECRET=defineSecret("RAZORPAY_KEY_SECRET");
const RAZORPAY_WEBHOOK_SECRET=defineSecret("RAZORPAY_WEBHOOK_SECRET");

function razorpayAuthHeader(){
  return "Basic "+Buffer.from(`${RAZORPAY_KEY_ID.value()}:${RAZORPAY_KEY_SECRET.value()}`).toString("base64");
}
async function razorpayRequest(path,options={}){
  const response=await fetch("https://api.razorpay.com/v1"+path,{
    ...options,
    headers:{Authorization:razorpayAuthHeader(),"Content-Type":"application/json",...(options.headers||{})}
  });
  const text=await response.text();
  let data={};
  try{data=text?JSON.parse(text):{}}catch{data={error:{description:text}}}
  if(!response.ok)throw new Error(data?.error?.description||"Razorpay API request failed.");
  return data;
}
function safeEqualHex(a,b){
  if(typeof a!=="string"||typeof b!=="string"||a.length!==b.length)return false;
  try{return crypto.timingSafeEqual(Buffer.from(a,"hex"),Buffer.from(b,"hex"))}catch{return false}
}
function webhookSignature(body,secret){
  return crypto.createHmac("sha256",secret).update(body).digest("hex");
}
function examPaymentWindowOpen(exam){
  const end=exam?.paymentEndMs!=null?Number(exam.paymentEndMs):(exam?.paymentEnd?new Date(exam.paymentEnd).getTime():null);
  return end==null||(!Number.isNaN(end)&&Date.now()<=end);
}
async function markPaymentSuccessful({applicationNumber,orderId,paymentId,amountPaise,signature,source}){
  const appRef=db.doc(`applications/${applicationNumber}`);
  const paymentRef=db.doc(`payments/${orderId}`);
  await db.runTransaction(async tx=>{
    const appSnap=await tx.get(appRef);
    const paymentSnap=await tx.get(paymentRef);
    if(!appSnap.exists)throw new Error("Application not found.");
    const app=appSnap.data();
    if(app.paymentStatus==="Successful")return;
    if(app.paymentOrderId!==orderId)throw new Error("Payment order does not match the application.");
    const examSnap=await tx.get(db.doc(`exams/${app.examId||"default"}`));
    const exam=examSnap.exists?examSnap.data():{};
    const expected=Math.round(Number(exam.fee||0)*100);
    if(expected<=0||amountPaise!==expected)throw new Error("Payment amount does not match the configured application fee.");
    tx.set(paymentRef,{
      applicationNumber,authUid:app.authUid||"",gateway:"razorpay",orderId,
      transactionId:paymentId,paymentReference:paymentId,
      amount:Number((amountPaise/100).toFixed(2)),amountPaise,currency:"INR",
      status:"Successful",verificationSource:source,
      signature:source==="checkout"?signature||null:null,
      verifiedAt:admin.firestore.FieldValue.serverTimestamp(),
      updatedAt:admin.firestore.FieldValue.serverTimestamp(),
      createdAt:paymentSnap.exists?(paymentSnap.data().createdAt||admin.firestore.FieldValue.serverTimestamp()):admin.firestore.FieldValue.serverTimestamp()
    },{merge:true});
    tx.update(appRef,{
      paymentStatus:"Successful",paymentOrderId:orderId,paymentId,
      paymentVerifiedAt:admin.firestore.FieldValue.serverTimestamp(),
      updatedAt:admin.firestore.FieldValue.serverTimestamp()
    });
  });
}

exports.createRazorpayOrder=onCall({secrets:[RAZORPAY_KEY_ID,RAZORPAY_KEY_SECRET]},async request=>{
  if(!request.auth)throw new HttpsError("unauthenticated","Please sign in again.");
  const applicationNumber=String(request.data?.applicationNumber||"").trim();
  if(!applicationNumber)throw new HttpsError("invalid-argument","Application number is required.");
  const appRef=db.doc(`applications/${applicationNumber}`);
  const appSnap=await appRef.get();
  if(!appSnap.exists||appSnap.data().authUid!==request.auth.uid)throw new HttpsError("permission-denied","Application access denied.");
  const app=appSnap.data();
  if(app.paymentStatus==="Successful")throw new HttpsError("failed-precondition","Payment is already successful.");
  const examSnap=await db.doc(`exams/${app.examId||"default"}`).get();
  if(!examSnap.exists)throw new HttpsError("failed-precondition","Exam configuration not found.");
  const exam=examSnap.data();
  if(exam.paymentRequired===false)return {required:false};
  if(!examPaymentWindowOpen(exam))throw new HttpsError("failed-precondition","The payment window has closed.");
  const amountPaise=Math.round(Number(exam.fee||0)*100);
  if(!Number.isFinite(amountPaise)||amountPaise<=0)throw new HttpsError("failed-precondition","Application fee is not configured.");
  const order=await razorpayRequest("/orders",{
    method:"POST",
    body:JSON.stringify({amount:amountPaise,currency:"INR",receipt:applicationNumber,notes:{applicationNumber,examId:app.examId||"default"}})
  });
  await db.runTransaction(async tx=>{
    const fresh=await tx.get(appRef);
    if(!fresh.exists||fresh.data().authUid!==request.auth.uid)throw new Error("Application changed or access denied.");
    tx.update(appRef,{
      paymentOrderId:order.id,paymentOrderAmount:amountPaise,
      paymentOrderCreatedAt:admin.firestore.FieldValue.serverTimestamp(),
      updatedAt:admin.firestore.FieldValue.serverTimestamp()
    });
    tx.set(db.doc(`payments/${order.id}`),{
      applicationNumber,authUid:request.auth.uid,gateway:"razorpay",orderId:order.id,
      amount:Number((amountPaise/100).toFixed(2)),amountPaise,currency:"INR",
      status:"Pending",createdAt:admin.firestore.FieldValue.serverTimestamp(),
      updatedAt:admin.firestore.FieldValue.serverTimestamp()
    });
  });
  return {required:true,keyId:RAZORPAY_KEY_ID.value(),orderId:order.id,amount:amountPaise,currency:"INR",description:`Application Fee - ${applicationNumber}`};
});

exports.verifyRazorpayPayment=onCall({secrets:[RAZORPAY_KEY_SECRET,RAZORPAY_KEY_ID]},async request=>{
  if(!request.auth)throw new HttpsError("unauthenticated","Please sign in again.");
  const applicationNumber=String(request.data?.applicationNumber||"").trim();
  const orderId=String(request.data?.orderId||"").trim();
  const paymentId=String(request.data?.paymentId||"").trim();
  const signature=String(request.data?.signature||"").trim();
  if(!applicationNumber||!orderId||!paymentId||!signature)throw new HttpsError("invalid-argument","Payment verification data is incomplete.");
  const appSnap=await db.doc(`applications/${applicationNumber}`).get();
  if(!appSnap.exists||appSnap.data().authUid!==request.auth.uid)throw new HttpsError("permission-denied","Application access denied.");
  const app=appSnap.data();
  if(app.paymentOrderId!==orderId)throw new HttpsError("failed-precondition","This payment order is not linked to the application.");
  if(app.paymentStatus==="Successful")return {success:true,status:"Successful"};
  const expectedSignature=crypto.createHmac("sha256",RAZORPAY_KEY_SECRET.value()).update(`${orderId}|${paymentId}`).digest("hex");
  if(!safeEqualHex(expectedSignature,signature))throw new HttpsError("permission-denied","Payment signature verification failed.");
  const payment=await razorpayRequest(`/payments/${encodeURIComponent(paymentId)}`,{method:"GET"});
  const examSnap=await db.doc(`exams/${app.examId||"default"}`).get();
  const expectedAmount=Math.round(Number(examSnap.exists?examSnap.data().fee:0)*100);
  if(payment.order_id!==orderId||payment.status!=="captured"||Number(payment.amount)!==expectedAmount)throw new HttpsError("failed-precondition","Payment is not captured or the amount does not match.");
  await markPaymentSuccessful({applicationNumber,orderId,paymentId,amountPaise:Number(payment.amount),signature,source:"checkout"});
  return {success:true,status:"Successful",paymentId};
});

exports.razorpayWebhook=onRequest({secrets:[RAZORPAY_WEBHOOK_SECRET,RAZORPAY_KEY_ID,RAZORPAY_KEY_SECRET]},async(req,res)=>{
  if(req.method!=="POST"){res.status(405).send("Method Not Allowed");return;}
  const raw=Buffer.isBuffer(req.rawBody)?req.rawBody:Buffer.from(JSON.stringify(req.body||{}));
  const signature=req.get("X-Razorpay-Signature")||"";
  if(!safeEqualHex(webhookSignature(raw,RAZORPAY_WEBHOOK_SECRET.value()),signature)){res.status(401).send("Invalid signature");return;}
  const event=req.body||{};
  const eventId=req.get("X-Razorpay-Event-Id")||"";
  if(eventId){
    const existing=await db.doc(`razorpayWebhookEvents/${eventId}`).get();
    if(existing.exists){res.status(200).send("OK");return;}
  }
  const entity=event?.payload?.payment?.entity;
  const orderId=entity?.order_id;
  try{
    if(orderId&&event.event==="payment.captured"){
      const paymentSnap=await db.doc(`payments/${orderId}`).get();
      if(paymentSnap.exists){
        const p=paymentSnap.data();
        await markPaymentSuccessful({applicationNumber:p.applicationNumber,orderId,paymentId:entity.id,amountPaise:Number(entity.amount||0),source:"webhook"});
      }
    }else if(orderId&&event.event==="payment.failed"){
      const paymentRef=db.doc(`payments/${orderId}`);
      const paymentSnap=await paymentRef.get();
      if(paymentSnap.exists&&paymentSnap.data().status!=="Successful"){
        await paymentRef.set({
          status:"Failed",transactionId:entity.id||"",paymentReference:entity.id||"",
          failureReason:entity.error_description||"",updatedAt:admin.firestore.FieldValue.serverTimestamp()
        },{merge:true});
        await db.doc(`applications/${paymentSnap.data().applicationNumber}`).set({
          paymentStatus:"Failed",updatedAt:admin.firestore.FieldValue.serverTimestamp()
        },{merge:true});
      }
    }
    if(eventId)await db.doc(`razorpayWebhookEvents/${eventId}`).set({receivedAt:admin.firestore.FieldValue.serverTimestamp(),event:event.event||""});
    res.status(200).send("OK");
  }catch(e){
    logger.error("Razorpay webhook processing failed",{event:event.event||"",orderId,error:e?.message});
    res.status(500).send("Retry");
  }
});
