const {onDocumentWritten}=require("firebase-functions/v2/firestore");
const {logger}=require("firebase-functions");
const admin=require("firebase-admin");

admin.initializeApp();
const db=admin.firestore();

exports.createAdmitCardDraftOnFinalSubmit=onDocumentWritten("applications/{applicationNumber}",async event=>{
  const after=event.data?.after;
  if(!after?.exists) return null;
  const a=after.data();
  if(a.status!=="Final Submitted"||a.paymentStatus!=="Successful") return null;

  const id=event.params.applicationNumber;
  const ref=db.doc(`admitCards/${id}`);
  const existing=await ref.get();
  const old=existing.exists?existing.data():{};
  if(old.published===true) return null;

  const examId=a.examId||"default";
  const examSnap=await db.doc(`exams/${examId}`).get();
  const exam=examSnap.exists?examSnap.data():{};

  await ref.set({
    applicationNumber:id,
    authUid:a.authUid,
    candidateName:a.personal?.fullName||"",
    fatherName:a.personal?.fatherName||"",
    examId,
    examName:exam.examName||"",
    examPost:a.personal?.examPost||"",
    examLanguage:a.personal?.examLanguage||exam.language||"",
    examDate:exam.examDate||"",
    requiredId:"Valid Government Photo ID",
    instructions:"Follow all instructions issued by the examination authority.",
    allowedItems:"As per examination instructions.",
    published:false,
    status:old.status||"Draft",
    version:Number(old.version||1),
    createdAt:old.createdAt||admin.firestore.FieldValue.serverTimestamp(),
    updatedAt:admin.firestore.FieldValue.serverTimestamp(),
    autoGenerated:true
  },{merge:true});

  logger.info("Admit-card draft ensured",{applicationNumber:id,examId});
  return null;
});