const {onDocumentWritten}=require("firebase-functions/v2/firestore");
const {logger}=require("firebase-functions");
const admin=require("firebase-admin");

admin.initializeApp();
const db=admin.firestore();

function rollString(prefix,start,width,n){
  return String(prefix||"")+String(n).padStart(Math.max(1,Number(width)||6),"0");
}

exports.createAdmitCardDraftOnFinalSubmit=onDocumentWritten("applications/{applicationNumber}",async event=>{
  const after=event.data?.after;
  if(!after?.exists) return null;
  const a=after.data();
  if(a.status!=="Final Submitted"||a.paymentStatus!=="Successful") return null;

  const id=event.params.applicationNumber;
  const examId=a.examId||"default";
  const examSnap=await db.doc(`exams/${examId}`).get();
  const exam=examSnap.exists?examSnap.data():{};
  if(exam.autoAdmitDraft===false) return null;

  const ref=db.doc(`admitCards/${id}`);
  const existing=await ref.get();
  const old=existing.exists?existing.data():{};
  if(old.published===true) return null;

  let rollNumber=old.rollNumber||"";
  if(!rollNumber){
    const counterRef=db.doc(`counters/admit_${examId}`);
    const counter=await db.runTransaction(async tx=>{
      const snap=await tx.get(counterRef);
      const current=Number(snap.exists?snap.data().nextNumber:(
        exam.rollStart??100001
      ));
      if(!Number.isFinite(current)||current<0) throw new Error("Invalid admit roll counter");
      tx.set(counterRef,{
        examId,
        nextNumber:current+1,
        updatedAt:admin.firestore.FieldValue.serverTimestamp()
      },{merge:true});
      return current;
    });
    rollNumber=rollString(exam.rollPrefix,exam.rollStart,exam.rollWidth,counter);
  }

  await ref.set({
    applicationNumber:id,
    authUid:a.authUid,
    candidateName:a.personal?.fullName||"",
    fatherName:a.personal?.fatherName||"",
    examId,
    examName:exam.examName||"",
    examPost:a.personal?.examPost||"",
    examLanguage:a.personal?.examLanguage||exam.language||"",
    examDate:exam.examDate||"",
    requiredId:"Valid Government Photo ID",
    instructions:"Follow all instructions issued by the examination authority.",
    allowedItems:"As per examination instructions.",
    published:false,
    status:old.status||"Draft",
    version:Number(old.version||1),
    rollNumber,
    createdAt:old.createdAt||admin.firestore.FieldValue.serverTimestamp(),
    updatedAt:admin.firestore.FieldValue.serverTimestamp(),
    autoGenerated:true
  },{merge:true});

  logger.info("Admit-card draft ensured",{applicationNumber:id,examId,rollNumber});
  return null;
});